baseURL = 'https://abedef.ca/'
languageCode = 'en-us'
title = "Abed's Blog"
theme = 'PaperMod'

[module]
[[module.imports]]
  path = 'github.com/adityatelange/hugo-PaperMod'

[params.homeInfoParams]
  title = "Abed's Blog"
  content = "Musings in game development, computer graphics, and infrastructure automation."

[[params.socialIcons]]
  name = "linkedin"
  url = "https://linkedin.com/in/abedef"